### ISSUE TITLE
trxdriver

### ISSUE THREAD

**Issue by DL8YBQ** [dj0abr/QO100_Transceiver#2]
Guten Abend,

hier der Hartmut, DL8YBQ aus Herten.

Den ganzen Abend versuche ich den QO100 Transceiver auf einem Raspberry 3b+ zum laufen zu bekommen. Es scheitert wohl an der fehlenden trxdriver Datei. Mehrmals alles neu installiert, jedoch ohne Erfolg. Ich bin für jeden Tipp, ggf. auch zum Thema Soundkarte, dankbar. Der Pluto ist per USB mit dem Raspi verbunden.

73 de Hartmut - DL8YBQ

**Comment by dj0abr** [comment]
Hallo Hartmut,

ich habe heute die Prozedur am Raspi nochmal von Anfang an durchgespielt und jeden Schritt dokumentiert, siehe hier:
https://wiki.amsat-dl.org/doku.php?id=de:plutotrx:raspi

abgesehen davon ist der 3B+ leider zu langsam. Man braucht einen Raspberry 4.

vy 73, Kurt, DJ0ABR

**Comment by DL8YBQ** [comment]
Hallo Kurt,

vielen Dank für deine prompte Antwort und der Dokumentation. Ich halte jetzt erstmal Ausschau nach einem Odroid-C4.

73 de Hartmut - DL8YBQ
