### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by DL5FCW** [dj0abr/QO100_Transceiver#4]
Hallo,
ich habe das Image V1.6 installiert und der Transceiver funktioniert.
Nun wollte ich ein update machen und bin Schritt für Schritt nach deiner Anleitung gegangen.
Leider stoppt der Update  mit einer  Fehlermeldung, hier her Verlauf:
---------------------------------------------------------------------------------------------
pi@QO100-TransceiverRaspberry:~ $ cd QO100_Transceiver
pi@QO100-TransceiverRaspberry:~/QO100_Transceiver $ git pull https://github.com/dj0abr/QO100_Transceiver
Von https://github.com/dj0abr/QO100_Transceiver
 * branch            HEAD       -> FETCH_HEAD
Aktualisiere 912e754..7afe78b
error: Ihre lokalen Änderungen in den folgenden Dateien würden durch den Merge
überschrieben werden:
        Release/bcn_fftcfg
        Release/fftcfg
        libkmaudio/libkmaudio_interface.cpp
        liquid/liquiddrv_modulator.cpp
Bitte committen oder stashen Sie Ihre Änderungen, bevor Sie mergen.
Abbruch
pi@QO100-TransceiverRaspberry:~/QO100_Transceiver $
------------------------------------------------------------------------------
Ich muss leider sagen dass ich auf dem Raspberry ein absoluter Anfänger bin

73 Günter DL5FCW

**Comment by dj0abr** [comment]
Hallo Günter,

ich habe die Beschreibung zum "Update" in der Anleitung entsprechend geändert.

[https://wiki.amsat-dl.org/doku.php?id=en:plutotrx:installation](url)

vy 73
Kurt, DJ0ABR

**Comment by DL5FCW** [comment]
Hallo Kurt,

Vielen Dank, jetzt geht es

vy73 Günter DL5FCW
